### ISSUE TITLE
Routing doesn't work

### ISSUE THREAD

**Issue by stvno** [WorldBank-Transport/traffic-engine-app#1]
If I click on the map the various points appear (green, blue and red) but no route is calculated, nor are the graphs being updated

**Comment by stvno** [comment]
some more digging: it might be that the otp graph wasn't created, however when it is I get this error:

[qtp1788447785-57] INFO org.opentripplanner.routing.impl.GraphPathFinder - Vertex not found: -6.143669618850388,106.81517601013182 : -6.151093949903108,106.81723594665527
[qtp1788447785-57] ERROR spark.webserver.MatcherFilter -
org.opentripplanner.routing.error.VertexNotFoundException: vertices not found: [from, to]
        at org.opentripplanner.routing.core.RoutingContext.check(RoutingContext.java:349)
        at org.opentripplanner.routing.core.RoutingRequest.setRoutingContext(RoutingRequest.java:810)
        at org.opentripplanner.routing.impl.GraphPathFinder.getPaths(GraphPathFinder.java:96)
        at org.opentripplanner.routing.impl.GraphPathFinder.getGraphPathsConsideringIntermediates(GraphPathFinder.java:270)
        at org.opentripplanner.routing.impl.GraphPathFinder.graphPathFinderEntryPoint(GraphPathFinder.java:195)
        at io.opentraffic.engine.app.routing.Routing.route(Routing.java:76)
        at io.opentraffic.engine.app.TrafficEngineApp.lambda$main$22(TrafficEngineApp.java:809)
        at spark.SparkBase$1.handle(SparkBase.java:311)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:159)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:60)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:451)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
        at java.lang.Thread.run(Thread.java:745)
[qtp1788447785-132] INFO org.opentripplanner.routing.impl.GraphPathFinder - Vertex not found: -6.143669618850388,106.81517601013182 : -6.151093949903108,106.81723594665527
[qtp1788447785-132] ERROR spark.webserver.MatcherFilter -
org.opentripplanner.routing.error.VertexNotFoundException: vertices not found: [from, to]
        at org.opentripplanner.routing.core.RoutingContext.check(RoutingContext.java:349)
        at org.opentripplanner.routing.core.RoutingRequest.setRoutingContext(RoutingRequest.java:810)
        at org.opentripplanner.routing.impl.GraphPathFinder.getPaths(GraphPathFinder.java:96)
        at org.opentripplanner.routing.impl.GraphPathFinder.getGraphPathsConsideringIntermediates(GraphPathFinder.java:270)
        at org.opentripplanner.routing.impl.GraphPathFinder.graphPathFinderEntryPoint(GraphPathFinder.java:195)
        at io.opentraffic.engine.app.routing.Routing.route(Routing.java:76)
        at io.opentraffic.engine.app.TrafficEngineApp.lambda$main$22(TrafficEngineApp.java:809)
        at spark.SparkBase$1.handle(SparkBase.java:311)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:159)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:60)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:451)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
        at java.lang.Thread.run(Thread.java:745)

**Comment by stvno** [comment]
Apparently it was a matter of lack of data, I've been feeding the app more data and now the routing works
